### ISSUE TITLE
Seems to have stopped working

### ISSUE THREAD

**Issue by rebmcr** [Mothrakk/TTVGA#2]
The giftbox icon just sits there under the chat now — nothing has changed on my system since I last saw it working correctly, so I think Twitch have probably changed their Javascript.

Also, the support link on addons.mozilla.org still points to what I think is your old username, https://github.com/Mothrakk

**Comment by loigom** [comment]
Hey, thanks for the report. Twitch probably changed their HTML layout so
the script just needs some elementary changes to find the appropriate
elements.

I'm in my final 3 weeks of conscription so I can't fix it until mid-June
(no computer access). If you'd like, you can fix it yourself, make a pull
request and I'll make you a contributor!
